# Generated by Django 5.0.4 on 2024-05-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0003_alter_game_id_alter_gamestate_id_alter_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_charge_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
