# Generated by Django 5.0.4 on 2024-05-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0004_payment_stripe_charge_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameState',
        ),
    ]
